version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
